### ISSUE TITLE
Failed to access ‘*.pr1.tagAlign.gz’

### ISSUE THREAD

**Issue by dcdxy** [ENCODE-DCC/chip-seq-pipeline2#37] opened 2018-11-13 14:57 UTC
I received the following error message on two separate runs of the TF pipeline (first with MACS2 peak calling on 3 WT replicate PE FASTQs, second with spp peak calling on 3 WT and 3 control PE FASTQs):

`[2018-11-12 16:41:57,70] [error] WorkflowManagerActor Workflow 3466d7a1-80d8-4d4a-b8ac-41f3fa027979 failed (during ExecutingWorkflowState): Job chip.spr:1:1 exited with return code 1 which has not been declared as a valid return code. See 'continueOnReturnCode' runtime attribute for more details.`

which arises from:

```
ln: failed to access ‘*.pr1.tagAlign.gz’: No such file or directory
ln: failed to access ‘*.pr2.tagAlign.gz’: No such file or directory
```
Any help would be appreciated.

**Details:**
I installed AQUAS on a SGE cluster.
**Cromwell:** cromwell 34-unknown-SNAP
**Conda:** conda 4.3.30

**Logs:** [debug_37.tar.gz](https://github.com/ENCODE-DCC/chip-seq-pipeline2/files/2576747/debug_37.tar.gz)

**Comment by leepc12** [comment] 2018-11-13 17:22
Duplicate of issue #22 . Let's discuss it there.

**Closed by leepc12** 2018-11-13 17:22 UTC
