### ISSUE TITLE
SLURM sbatch failure?

### ISSUE THREAD

**Issue by simingzhang** [ENCODE-DCC/chip-seq-pipeline2#146] opened 2020-04-03 07:10 UTC
Hi, I'm trying to run the pipeline on scg4 (slurm). 
The script I'm running is:
caper run chip.wdl -c $caper_config --singularity -i $INPUT --tmp-dir $OUTPUT_DIR --out-dir $OUTPUT_DIR

Error in metadata.json:
    "failures": [
        {
            "causedBy": [
                {
                    "message": "java.lang.RuntimeException: Could not find job ID from stdout file.Check the stderr file for possible errors: /labs/dflev/siming/chipseq/encode_analysis_pipeline/chipseq_nano3_test2/chip/0f069612-8711-4c13-b728-560bb8ea259f/call-read_genome_tsv/execution/stderr.submit",
                    "causedBy": [
                        {
                            "message": "Could not find job ID from stdout file.Check the stderr file for possible errors: /labs/dflev/siming/chipseq/encode_analysis_pipeline/chipseq_nano3_test2/chip/0f069612-8711-4c13-b728-560bb8ea259f/call-read_genome_tsv/execution/stderr.submit",
                            "causedBy": []
                        }
                    ]
                }
            ],
            "message": "Workflow failed"
        }
    ],

**Comment by leepc12** [comment] 2020-04-03 15:02
Can you run it as described in the documentation?
It should be something like `sbatch .. --wrap "caper run ..."`.

**Comment by leepc12** [comment] 2020-04-03 23:24
I reproduced the same error on Stanford Sherlock. I will look into this.

**Comment by simingzhang** [comment] 2020-04-03 23:36
I tried rerunning by following the web directions and switched to conda (instead of using singularity) since that seemed more recommended. It ran for a bit but I got a different error. 

My new script:
conda activate encode-chip-seq-pipeline
cd $OUTPUT_DIR
sbatch -A aeurban -J chipseq3 --export=ALL --mem 3G -t 7-0 --wrap "caper run /labs/dflev/siming/software/chip-seq-pipeline2/chip.wdl -i $INPUT --out-dir $OUTPUT_DIR"

I attached the metadata file (had to rename to .txt because I didn't know how to upload .json files)
[metadata.txt](https://github.com/ENCODE-DCC/chip-seq-pipeline2/files/4430367/metadata.txt)

**Comment by simingzhang** [comment] 2020-04-04 02:17
I reran it with a fresh install of conda and it's running successfully further into the pipeline. But an error occurs with call-overlap_pr. 

This is my new code.
`conda activate encode-chip-seq-pipeline
cd $OUTPUT_DIR
sbatch -A aeurban -J chipseq --export=ALL --mem 3G -t 7-0 --wrap "caper run /labs/dflev/siming/software/chip-seq-pipeline2/chip.wdl -i $INPUT --out-dir $OUTPUT_DIR"


[metadata.txt](https://github.com/ENCODE-DCC/chip-seq-pipeline2/files/4430618/metadata.txt)

**Comment by leepc12** [comment] 2020-04-06 17:24
This turns out to be bug of a python module `pyhocon` > 0.3.51, which does not correctly parse double backslashes in JSON.

Please check your `python` version with:
```bash
$ pip list pyhocon
```

If that is > 0.3.51 then downgrade it to 0.3.51.
```bash
$ pip install pyhocon==0.3.51
```

So pipeline worked with pipeline's Conda environment since `python` inside the Conda env is <= 0.3.51. Check pyhocon version inside the conda env too.


I will look into more in details about this.
```bash
$ source activate encode-chip-seq-pipeline
$ pip list pyhocon  # my conda env has 0.3.51
...
pyhocon                  0.3.51
...
```

**Comment by leepc12** [comment] 2020-04-06 20:00
It turns out that `pyhocon` 0.3.54 works correctly and versions <0.3.53 are buggy.
See details in this [PR](https://github.com/ENCODE-DCC/caper/pull/65).

Once this PR is merged then I will make a new release for Caper.
Until then use downgraded `pyhocon` 0.3.51.

For a new release of Caper (it will be 0.8.2), `pip uninstall caper` and reinstall it, then pip will install bug-fixed `pyhocon` >= 0.3.53.

**Comment by simingzhang** [comment] 2020-04-06 20:59
the pyhocan version in the conda environment is 0.3.51. But outside the conda environment doesn't seem to have pyhocan. Do I need to install it as well? 

Also, just to clarify, is this bug related to my original post (using singularity) or to the call-overlap_pr error when using the conda environment? Apologies if I should have made a new post and confused the issue.

**Comment by leepc12** [comment] 2020-04-06 22:00
@simingzhang: That's why it worked. I will make a new release for Caper today.

About your question, if you keep using Conda then no. But if you want to use singularity outside of the conda environment, then yes just upgrade Caper then it will automatically install/upgrade pyhocon.

**Comment by leepc12** [comment] 2020-07-07 21:11
Closing this due to long inactivity.

**Closed by leepc12** 2020-07-07 21:11 UTC
